build: false

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"

  matrix:

    # Pre-installed Python versions, which Appveyor may upgrade to
    # a later point release.
    # See: http://www.appveyor.com/docs/installed-software#python


#    - PYTHON: "C:\\Python266"
#      PYTHON_VERSION: "2.6.6"
#      PYTHON_ARCH: "32"

#    - PYTHON: "C:\\Python266-x64"
#      PYTHON_VERSION: "2.6.6"
#      PYTHON_ARCH: "64"

#    - PYTHON: "C:\\Python27"
#      PYTHON_VERSION: "2.7.x"
#      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64"

#    - PYTHON: "C:\\Python34"
#      PYTHON_VERSION: "3.4.x"
#      PYTHON_ARCH: "32"

#    - PYTHON: "C:\\Python34-x64"
#      PYTHON_VERSION: "3.4.x"
#      PYTHON_ARCH: "64"

#    - PYTHON: "C:\\Python35"
#      PYTHON_VERSION: "3.5.0"
#      PYTHON_ARCH: "32"

#    - PYTHON: "C:\\Python35-x64"
#      PYTHON_VERSION: "3.5.0"
#      PYTHON_ARCH: "64"

#    - PYTHON: "C:\\Python36"
#      PYTHON_VERSION: "3.6.0"
#      PYTHON_ARCH: "32"

#    - PYTHON: "C:\\Python36-x64"
#      PYTHON_VERSION: "3.6.0"
#      PYTHON_ARCH: "64"

#    - PYTHON: "C:\\Python37"
#      PYTHON_VERSION: "3.7.0"
#      PYTHON_ARCH: "32"

#    - PYTHON: "C:\\Python37-x64"
#      PYTHON_VERSION: "3.7.0"
#      PYTHON_ARCH: "64"

  # For debug purpose only
  APPVEYOR_RDP_PASSWORD:  Azerty123!


install:
  # If there is a newer build queued for the same PR, cancel this one.
  # The AppVeyor 'rollout builds' option is supposed to serve the same
  # purpose but it is problematic because it tends to cancel builds pushed
  # directly to master instead of just PR builds (or the converse).
  # credits: JuliaLang developers.
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
          throw "There are newer queued builds for this pull request, failing early." }
  - ECHO "Filesystem root:"
  - ps: "ls \"C:/\""

  # Install Python (from the official .msi of http://python.org) and pip when not already installed.
  - ps: if (-not(Test-Path($env:PYTHON))) { & appveyor\install.ps1 }

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # Upgrade to the latest version of pip to avoid it displaying warnings
  # about it being out of date.
  - "python -m pip install --upgrade pip"

  - "python setup.py install"
  # TODO: remove this, and let the setup.py do the job
  - xcopy . c:\opsbro /O /X /E /H /K /Y /Q
  - dir c:\opsbro


build_script:
  - python --version

test_script:
  # Run the project tests
  - "%CMD_IN_ENV% python bin/opsbro"
  - echo "CLASSIC RUN"
  - python bin\opsbro agent start --one-shot
  - echo "SERVICE RUN"
  - "python -c \"import sys; print(sys.executable)\""
  # This should be available before go
  #- C:\Python27-x64\lib\site-packages\win32\pythonservice.exe
  #- sc create OpsBro binPath="C:\Python27-x64\python.exe C:\opsbro\bin\opsbro agent start" type=own error=ignore start=auto

  # CLEAN ALL logs
  - wevtutil cl System
  - wevtutil cl Application
  - "%CMD_IN_ENV% python c:/opsbro/bin/opsbro agent windows service-install"
  - sc start OpsBro || sc qc OpsBro && sc query OpsBro && wevtutil qe Application && wevtutil qe System && type c:\opsbro.log && bad
  - "%CMD_IN_ENV% python c:/opsbro/bin/opsbro agent info"
  - "%CMD_IN_ENV% python c:/opsbro/bin/opsbro collectors state"
  - "%CMD_IN_ENV% python c:/opsbro/bin/opsbro monitoring state"
  - "%CMD_IN_ENV% python c:/opsbro/bin/opsbro compliance state"
  - "%CMD_IN_ENV% python c:/opsbro/bin/opsbro collectors show"



#after_test:
  # If tests are successful, create binary packages for the project.
#  - "%CMD_IN_ENV% python setup.py bdist_wheel"
#  - "%CMD_IN_ENV% python setup.py bdist_wininst"
#  - "%CMD_IN_ENV% python setup.py bdist_msi"
#  - ps: "ls"


# ENABLE DEBUG MODE
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))